### - testes da API - o REST Client

### - Teste se o servidor está funcionando
GET http://localhost:3000/
Content-Type: application/json

### - Teste para Cadastrar o Usuário
POST http://localhost:3000/usuario
Content-Type: application/json

{
    "nome": "Adalberto",
    "email": "adalberto@gmail.com",
    "senha": "123"
}

### - Teste para Listar o Usuário

GET http://localhost:3000/usuarios
Content-Type: application/json

### - Teste para Consultar o Usuário
GET http://localhost:3000/usuario/1
Content-Type: application/json


### - Teste para Consultar o Usuário por nome
GET http://localhost:3000/usuario/buscar/marcos
Content-Type: application/json

### - Teste para Excluir o Usuário
DELETE http://localhost:3000/usuario/4
Content-Type: application/json

### - Teste para Atualizar o Usuário
PUT http://localhost:3000/usuario/3
Content-Type: application/json

{
    "nome": "Rodrigo",
    "email": "rodrigo@gmail.com",
    "senha": "456"
}
